default-extensions: DeriveGeneric
                  , DuplicateRecordFields
                  , EmptyCase
                  , FlexibleContexts
                  , FlexibleInstances
                  , GeneralizedNewtypeDeriving
                  , InstanceSigs
                  , MultiParamTypeClasses
                  , NamedFieldPuns
                  , OverloadedStrings
                  , ScopedTypeVariables
when:
- condition: os(darwin)
  then:
    ghc-options: []
  else:
    ghc-options:
    - -static
    cc-options:
    - -static
    ld-options:
    - -static
    - -pthread
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  dependencies:
  - aeson
  - containers
  - foldl
  - text
  - yaml
tests:
  manifest-generator-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - manifest-generator
    - bytestring
    - containers
    - foldl
    - hspec
    - QuickCheck
    - quickcheck-text
    - text
    - yaml
copyright: Copyright (c) 2019 Boclips
maintainer: engineering@boclips.com
dependencies:
- base >= 4.7 && < 5
- turtle >= 1.5.12 && < 1.6.0
name: manifest-generator
version: 0.1.0.0
extra-source-files: []
author: Avrono
github: boclips/manifest-generator
executables:
  render:
    source-dirs: app
    main: RenderCommand.hs
    other-modules: []
    ghc-options:
    - -main-is RenderCommand
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - manifest-generator
    - bytestring
    - text
    - yaml

  release:
    source-dirs: app
    main: ReleaseCommand.hs
    other-modules: []
    ghc-options:
    - -main-is ReleaseCommand
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - manifest-generator
description: Boclips Kubernetes Manifest Generator
