---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
    tag: "0.1.0"

inputs:
- name: source
- name: bin
  path: source/bin

outputs:
- name: image

params:
  CONTEXT: source

run:
  path: build

caches:
- path: cache
