---
jobs:

- name: build
  plan:
  - in_parallel:
    - get: source
      trigger: true
    - put: version
      params:
        bump: minor
  - task: build-app
    file: source/pipeline/tasks/build-app.yaml
  - task: copy-app-to-image
    privileged: true
    file: source/pipeline/tasks/copy-app-to-image.yaml
  - put: image
    params:
      image: image/image.tar
      additional_tags: version/version

resources:

- name: source
  type: git
  icon: github-circle
  source:
    branch: master
    uri: https://github.com/boclips/manifest-generator.git

- name: version
  type: semver
  icon: github-circle
  source:
    driver: git
    uri: git@github.com:boclips/versions.git
    branch: master
    file: manifest-generator
    private_key: ((versions.repo-key))

- name: image
  type: registry-image
  icon: docker
  source:
    repository: boclipsconcourse/manifest-generator
    username: boclipsconcourse
    password: ((docker-hub.password))
